---

- name: Delete the voting_config_exclusions (make all eligible again)
  become: yes
  become_user: "{{es_user}}"
  uri:
    url: "https://localhost:9200/_cluster/voting_config_exclusions"
    user: "{{es_api_basic_auth_username | default(omit)}}"
    password: "{{es_api_basic_auth_password | default(omit)}}"
    force_basic_auth: yes
    method: DELETE
    client_cert: "{{es_ssl_certificate if es_ssl_client_authentication=='required' else omit}}"
    client_key: "{{es_ssl_key if es_ssl_client_authentication=='required' else omit}}"
    validate_certs: no
  run_once: true

- name: Remove the cluster.routing.allocation.exclude._name
  become: yes
  become_user: "{{es_user}}"
  uri:
    url: "https://localhost:9200/_cluster/settings"
    user: "{{es_api_basic_auth_username | default(omit)}}"
    password: "{{es_api_basic_auth_password | default(omit)}}"
    force_basic_auth: yes
    method: PUT
    body_format: json
    body:
      "transient": { "cluster.routing.allocation.exclude._name": null }
    client_cert: "{{es_ssl_certificate if es_ssl_client_authentication=='required' else omit}}"
    client_key: "{{es_ssl_key if es_ssl_client_authentication=='required' else omit}}"
    validate_certs: no
  run_once: true
