---

- name: clusterverse | Deploy (and/or delete) the cluster VMs
  hosts: localhost
  gather_facts: false
  tasks:
    - assert: { that: "['clusterverse.clusterverse', 'dseeley.tasks_serial', 'dseeley.ansible_vault_pipe'] is subset(galaxy_collections.keys())", success_msg: "clusterverse collections dependencies are met", fail_msg: "Please ensure the clusterverse collections are installed: ansible-galaxy install -r requirements.yml)" }
      vars: { galaxy_collections: "{{lookup('pipe', 'ansible-galaxy collection list --format=json', errors='ignore') | from_json | json_query('*') | combine }}" }
      tags: ["always"]

    - { include_role: { name: "clusterverse.clusterverse.clean", apply: { tags: ["clusterverse_clean"]} }, tags: ["clusterverse_clean"], when: "clean is defined" }
    - { include_role: { name: "clusterverse.clusterverse.create", apply: { tags: ["clusterverse_create"]} }, tags: ["clusterverse_create"] }
    - { include_role: { name: "clusterverse.clusterverse.dynamic_inventory", apply: { tags: ["always"]} }, tags: ["always"] }

- name: clusterverse | Validate remote python version is supported by local ansible version; import_playbook 'raw_python39_install.yml' if not
  hosts: all:!not_target_hosts
  gather_facts: false
  tags: ["clusterverse_create"]
  tasks:
    - { ansible.builtin.wait_for: { port: 22, host: '{{ ansible_host }}', timeout: 30 }, delegate_to: localhost }
    - { ansible.builtin.setup: { gather_subset: ["python"] }, ignore_errors: true, register: r__setup__python_version_check, vars: { ansible_ssh_retries: 10 } }
    - { include_role: { name: "clusterverse.clusterverse.config", tasks_from: "raw_python39_install.yml" }, when: r__setup__python_version_check.failed is defined and r__setup__python_version_check.failed }

- name: clusterverse | Configure the cluster VM OSs (excluding not-being-redeployed hosts)
  hosts: all:!not_target_hosts
  gather_facts: false
  tasks:
    - { wait_for_connection: "", timeout: 300, tags: ["always"] }
    - { include_role: { name: "clusterverse.clusterverse.config", apply: { tags: ["clusterverse_config"]} }, tags: ["clusterverse_config"] }


###### elastic roles ######
- name: elastic | load clusterverse dependencies (if excluded due to --skips-tags)
  hosts: all
  tasks:
    - { include_role: { name: "clusterverse.clusterverse._dependencies", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_config' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_config, this will ensure the variables from /cluster_defs are loaded.
    - { include_role: { name: "clusterverse.clusterverse.cluster_hosts", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_create' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_create, this will ensure cluster_suffix is defined.

- name: elastic | ssl_ownca
  hosts: all:localhost
  tasks: [ { include_role: { name: "elastic/ssl_ownca", apply: { tags: ["elastic_ssl_ownca"] } }, tags: ["elastic_ssl_ownca"] } ]

- name: elastic | elasticsearch   # master nodes must be running first (reverse_sorted)
  hosts: all:!kibana
  order: reverse_sorted
  tasks: [ { include_role: { name: "elastic/elasticsearch/data_master_node", apply: { tags: ["elastic_elasticsearch"]} }, tags: ["elastic_elasticsearch"] } ]

- name: elastic | elasticsearch test
  hosts: data[0]
  gather_facts: false
  tasks: [ { include_role: { name: "elastic/elasticsearch/test", apply: { tags: ["elastic_elasticsearch_test"]} }, tags: ["elastic_elasticsearch_test"] } ]

- name: elastic | kibana
  hosts: kibana
  tasks:
    - { include_role: { name: "elastic/kibana", apply: { tags: ["elastic_kibana"]} }, tags: ["elastic_kibana"] }
###### elastic roles ######


- name: clusterverse | Perform cluster readiness operations. 'post_deploy.yml' is run after every cluster deploy; 'post_redeploy.yml' is run after redeploy (or cluster deploy if this is not a redeploy)
  hosts: localhost
  tasks:
    - { include_role: { name: "clusterverse.clusterverse.readiness", tasks_from: "post_deploy.yml" } }
    - { include_role: { name: "clusterverse.clusterverse.readiness", tasks_from: "post_redeploy.yml", apply: { tags: ["clusterverse_readiness"]} }, tags: ["clusterverse_readiness"] }
