---

- name: clusterverse/deploy | create (and/or optionally destroy) the cluster VMs
  hosts: localhost
  gather_facts: false
  tasks:
    - assert: { that: "['clusterverse.clusterverse', 'dseeley.tasks_serial', 'dseeley.ansible_vault_pipe'] is subset(galaxy_collections.keys())", success_msg: "clusterverse collections dependencies are met", fail_msg: "Please ensure the clusterverse collections are installed: ansible-galaxy install -r requirements.yml)" }
      vars: { galaxy_collections: "{{lookup('pipe', 'ansible-galaxy collection list --format=json', errors='ignore') | from_json | json_query('*') | combine }}" }
      tags: ["always"]

    - { name: "clusterverse/deploy | clusterverse.destroy", include_role: { name: "clusterverse.clusterverse.destroy", apply: { tags: ["clusterverse_destroy"]} }, tags: ["clusterverse_destroy"], when: "destroy_lifecycle is defined" }
    - { name: "clusterverse/deploy | clusterverse.create", include_role: { name: "clusterverse.clusterverse.create", apply: { tags: ["clusterverse_create"]} }, tags: ["clusterverse_create"] }
    - { name: "clusterverse/deploy | clusterverse.dynamic_inventory", include_role: { name: "clusterverse.clusterverse.dynamic_inventory", apply: { tags: ["always"]} }, tags: ["always"] }

- name: clusterverse/deploy | Configure the cluster VM OSs (excluding not-being-redeployed hosts)
  hosts: all:!not_target_hosts
  gather_facts: false
  tasks:
    - name: clusterverse/deploy | Validate remote python version is supported by local ansible version, import_playbook 'raw_python39_install.yml' if not
      block:
        - { name: "clusterverse/deploy | wait_for (port 22)", ansible.builtin.wait_for: { port: 22, host: '{{ ansible_host }}', timeout: 30 }, delegate_to: localhost }
        - { name: "clusterverse/deploy | gather_subset (python)", ansible.builtin.setup: { gather_subset: ["python"] }, ignore_errors: true, register: r__setup__python_version_check, vars: { ansible_ssh_retries: 10 } }
        - { name: "clusterverse/deploy | raw_python39_install.yml", include_role: { name: "clusterverse.clusterverse.config", tasks_from: "raw_python39_install.yml" }, when: r__setup__python_version_check.failed is defined and r__setup__python_version_check.failed }

    - { name: "clusterverse/deploy | wait_for_connection", wait_for_connection: "", timeout: 300, tags: ["always"] }
    - { name: "clusterverse/deploy | clusterverse.config", include_role: { name: "clusterverse.clusterverse.config", apply: { tags: ["clusterverse_config"]} }, tags: ["clusterverse_config"] }


###### elastic roles ######
- name: clusterverse/deploy/application | load clusterverse dependencies (if excluded due to --skips-tags)
  hosts: all
  gather_facts: false
  tasks:
    - { name: "application | clusterverse._dependencies", include_role: { name: "clusterverse.clusterverse._dependencies", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_config' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_config, this will ensure the variables from /cluster_defs are loaded.
    - { name: "application | clusterverse.cluster_hosts (get_cluster_hosts_state)", include_role: { name: "clusterverse.clusterverse.cluster_hosts", tasks_from: "get_cluster_hosts_state.yml", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_create' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_create, this will ensure cluster_suffix is defined.

- name: elastic | ssl_ownca
  hosts: all:localhost
  tasks: [ { include_role: { name: "elastic/ssl_ownca", apply: { tags: ["elastic_ssl_ownca"] } }, tags: ["elastic_ssl_ownca"] } ]

- name: elastic | elasticsearch   # master nodes must be running first (reverse_sorted)
  hosts: all:!kibana
  order: reverse_sorted
  tasks: [ { include_role: { name: "elastic/elasticsearch/data_master_node", apply: { tags: ["elastic_elasticsearch"]} }, tags: ["elastic_elasticsearch"] } ]

- name: elastic | elasticsearch test
  hosts: data[0]
  gather_facts: false
  tasks: [ { include_role: { name: "elastic/elasticsearch/test", apply: { tags: ["elastic_elasticsearch_test"]} }, tags: ["elastic_elasticsearch_test"] } ]

- name: elastic | kibana
  hosts: kibana
  tasks:
    - { include_role: { name: "elastic/kibana", apply: { tags: ["elastic_kibana"]} }, tags: ["elastic_kibana"] }
###### elastic roles ######


- name: clusterverse/deploy | Perform cluster readiness operations.  readiness_cnames and readiness_clean are so-tagged to ensure that during a redeeploy, they will be skipped, until after the cluster is redeployed.
  hosts: localhost
  gather_facts: false
  tasks:
    - { name: "clusterverse/deploy | clusterverse.readiness/reenable_systemd", include_role: { name: "clusterverse.clusterverse.readiness", tasks_from: "reenable_systemd.yml" } }
    - { name: "clusterverse/deploy | clusterverse.readiness/dns_cname", include_role: { name: "clusterverse.clusterverse.readiness", tasks_from: "dns_cname.yml", apply: { tags: ["readiness_cnames"]} }, tags: ["readiness_cnames"] }
    - { name: "clusterverse/deploy | clusterverse.readiness/clean_tmp", include_role: { name: "clusterverse.clusterverse.readiness", tasks_from: "clean_tmp.yml", apply: { tags: ["readiness_clean"]} }, tags: ["readiness_clean"] }
