---

- name: clusterverse/destroy | Destroy the cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - assert: { that: "['clusterverse.clusterverse', 'dseeley.tasks_serial', 'dseeley.ansible_vault_pipe'] is subset(galaxy_collections.keys())", success_msg: "clusterverse collections dependencies are met", fail_msg: "Please ensure the clusterverse collections are installed: ansible-galaxy install -r requirements.yml)" }
      vars: { galaxy_collections: "{{lookup('pipe', 'ansible-galaxy collection list --format=json', errors='ignore') | from_json | json_query('*') | combine }}" }
      tags: ["always"]

    - name: clusterverse/destroy | clusterverse.destroy (set destroy_lifecycle=_all_ as default - can be overridden by command line '-e destroy=...')
      include_role:
        name: "clusterverse.clusterverse.destroy"
      vars: { destroy_lifecycle: _all_ }

    - name: clusterverse/redeploy | clusterverse.readiness/clean_tmp
      include_role:
        name: "clusterverse.clusterverse.readiness"
        tasks_from: "clean_tmp.yml"
