---

roles:
  - name: clusterverse
    src: https://github.com/dseeley/clusterverse
    version: master

  - name: elasticsearch
    src: https://github.com/dseeley/elasticsearch_ansible
    version: master
