---

roles:
  - name: elastic
    src: https://github.com/clusterverse/elastic
    version: master

collections:
  - name: clusterverse.clusterverse
    version: ">=5.0.0,<5.1.0"
    source: https://galaxy.ansible.com

  - name: dseeley.tasks_serial
    version: ">=1.0.0,<2.0.0"
    source: https://galaxy.ansible.com

  - name: dseeley.ansible_vault_pipe
    version: ">=1.0.2,<2.0.0"
    source: https://galaxy.ansible.com

  # Optional, if using libvirt
  - name: dseeley.inventory_lookup
    version: ">=1.0.1,<2.0.0"
    source: https://galaxy.ansible.com

  - name: dseeley.libvirt
    version: ">=2.1.1,<3.0.0"
    source: https://galaxy.ansible.com
