---

- name: Stop elasticsearch service
  become: yes
  service:
    name: elasticsearch
    state: stopped
  delegate_to: "{{hosts_to_remove}}"
  register: elasticsearch_service_status
  until: elasticsearch_service_status.status.ActiveState == "inactive"
  retries: 30
  delay: 5
