---

# Need to do this when we manually add systemd service files to the filesystem
- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: yes
  throttle: 1

# Restart elasticsearch and ensure it is enabled
- name: restart elasticsearch
  become: yes
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
  throttle: 1
