---

- name: kibana/redeploy_predelete | hosts_to_remove
  debug: msg="{{hosts_to_remove | default('')}}"

- name: kibana/redeploy_predelete | gather service_facts
  service_facts:
  delegate_to: "{{item.name}}"
  delegate_facts: true
  loop: "{{hosts_to_remove}}"

- name: kibana/redeploy_predelete | stop kibana.service
  become: true
  service:
    name: kibana
    state: stopped
  delegate_to: "{{item.name}}"
  loop: "{{hosts_to_remove}}"
  when: "'kibana.service' in hostvars[item.name]['ansible_facts']['services']"

- name: kibana/redeploy_predelete | reconfigure kibana.yml - needs to have elasticsearch.hosts set to the new hosts (excluding the hosts_to_remove)
  block:
    - name: kibana/redeploy_predelete | kibana_nodes_to_keep
      debug: msg={{kibana_nodes_to_keep}}

    - name: kibana/redeploy_predelete | groups['data'] | difference(hosts_to_remove_elasticsearch | default([]) | map(attribute='name'))
      debug:
        msg: "{{ groups['data'] | difference(hosts_to_remove_elasticsearch | default([]) | map(attribute='name')) }}"

    - name: kibana/redeploy_predelete | Copy main config file
      template:
        src: "{{playbook_dir}}/roles/elastic/kibana/templates/opt/kibana/config/kibana.yml.j2"
        dest: "{{kibana_conf_dir}}/kibana.yml"
        owner: "{{kibana_user}}"
        group: "{{kibana_group}}"
        mode: '0644'
        force: true
      delegate_to: "{{item}}"
      loop: "{{ kibana_nodes_to_keep }}"

    - name: kibana/redeploy_predelete | restart kibana
      service:
        name: kibana
        state: restarted
      delegate_to: "{{item}}"
      loop: "{{ kibana_nodes_to_keep }}"
  become: true
  vars:
    kibana_nodes_to_keep: "{{ groups['kibana'] | difference(hosts_to_remove|map(attribute='name')) |list }}"
