---

# Need to do this when we manually add systemd service files to the filesystem
- name: reload systemd configuration
  become: true
  systemd:
    daemon_reload: true
  throttle: 1

## Restart elasticsearch nodes.  If this is not the initial install (the elasticsearch binary was not present), do each in-turn, ensuring each node is *really* back up (i.e. port 9200 is open) before restarting the next.
## This custom action plugin is a compromise, but there is apparently no alternative; see https://github.com/ansible/ansible/issues/80374
- name: restart elasticsearch
  become: true
  dseeley.tasks_serial.tasks_serial:
    tasks:
      - name: service
        args:
          name: elasticsearch
          state: restarted
          enabled: true
      - name: wait_for
        args:
          host: localhost
          port: 9200
          timeout: 300
  throttle: "{{ '1' if es_link_stat is defined and es_link_stat.stat.exists else '0' }}"
