---

# Need to do this when we manually add systemd service files to the filesystem
- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: yes

# Restart elasticsearch and ensure it is enabled
- name: restart elasticsearch
  become: yes
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
  when: es_restart_on_change or es_start_service
  notify: Wait for elasticsearch to startup

- name: Wait for elasticsearch to startup
  wait_for: host=localhost port=9200
  changed_when: true
