---

- name: Update api user password in .security index (setting elastic password here disables the bootstrap.password)
  uri:
    url: "https://localhost:9200/_security/user/{{es_api_basic_auth_username}}/_password"
    method: POST
    body_format: json
    body: "{ \"password\":\"{{es_api_basic_auth_password}}\" }"
    status_code: 200
    user: "{{es_api_basic_auth_username}}"
    password: "{{es_api_basic_auth_password}}"
    force_basic_auth: yes
    validate_certs: no
  when: "'bootstrap.password' not in elasticsearch_keystore_list.stdout_lines"
  run_once: yes

- name: Update other builtin user creds in .security index
  uri:
    url: "https://localhost:9200/_security/user/{{item.key}}/_password"
    method: POST
    body_format: json
    body: "{ \"password\":\"{{item.value}}\" }"
    status_code: 200
    user: "{{es_api_basic_auth_username}}"
    password: "{{es_api_basic_auth_password}}"
    force_basic_auth: yes
    validate_certs: no
  run_once: yes
  with_dict: "{{builtin_user_creds}}"
  when: "item.value != ''"

