---

# Need to do this when we manually add systemd service files to the filesystem
- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: yes
  throttle: 1

# Restart kibana and ensure it is enabled
- name: restart kibana
  become: yes
  service:
    name: kibana
    state: restarted
    enabled: yes
  register: kibana_service_status
  until: kibana_service_status.status.ActiveState == "active"
  retries: 30
  delay: 5
  throttle: 1
