---

# Need to do this when we manually add systemd service files to the filesystem
- name: reload systemd configuration
  become: true
  systemd:
    daemon_reload: true
  throttle: 1

## Restart kibana nodes.  If this is not the initial install (the kibana binary was not present), do each in-turn, ensuring each node is *really* back up (i.e. port 9200 is open) before restarting the next.
## This custom action plugin is a compromise, but there is apparently no alternative; see https://github.com/ansible/ansible/issues/80374
- name: restart kibana
  become: true
  dseeley.tasks_serial.tasks_serial:
    tasks:
      - name: service
        args:
          name: kibana
          state: restarted
          enabled: true
      - name: wait_for
        args:
          host: localhost
          port: "{{kibana_port | default(5601)}}"
          timeout: 300
  throttle: "{{ '1' if kibana_link_stat is defined and kibana_link_stat.stat.exists else '0' }}"
