---

- name: hostconfig | kernel tuning | Set swappiness to 0
  become: yes
  sysctl:
    name: vm.swappiness
    value: 0
    sysctl_set: yes
    state: present
    reload: yes

- name: hostconfig | Create Elasticsearch unix group
  become: yes
  group:
    name: "{{es_group}}"

- name: hostconfig | Add the Elasticsearch user
  become: yes
  user:
    name: "{{es_user}}"
    groups: "{{es_group}}"
    system: yes

- name: "hostconfig | Change {{es_data_dir}} data directory ownership "
  become: yes
  file:
    path: "{{es_data_dir}}"
    name: "{{es_user}}"
    group: "{{es_group}}"
    mode: 0755
    state: directory
