---

- include: hostconfig.yml

- include: install-binary.yml

- include: install-plugins.yml

- include: install-config.yml


## Fail if ES doesn't start up (assuming we asked it to)
- block:
  - meta: flush_handlers

  - wait_for:
      host: localhost
      port: 9200
      timeout: 30
    register: service_elasticsearch_status

  - name: Report status of elasticsearch if not running
    fail:
      msg: |
        service_elasticsearch_status is not running.
        Output of `systemctl status elasticsearch`:
        {{ service_elasticsearch_status.stdout }}
        {{ service_elasticsearch_status.stderr }}
    when: service_elasticsearch_status is failed


  - name: Apply ES templates
    become: yes
    uri:
      url: "http://localhost:9200/_template/{{item['name']}}"
      method: PUT
      status_code: 200
#      user: "{{es_api_basic_auth_username | default(omit)}}"
#      password: "{{es_api_basic_auth_password | default(omit)}}"
#      force_basic_auth: yes
      body_format: json
      body: "{{ item['content'] }}"
      validate_certs: no
    with_items: "{{ es_mapping_templates }}"
    notify: load-templates
    when: es_mapping_templates is defined
    delegate_to:

  when: es_restart_on_change and es_start_service