---

merge_dict_vars_list:
  - "./cluster_defs/"
  - "./cluster_defs/{{ cloud_type }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ clusterid | default() }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ clusterid | default() }}/{{ region }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ clusterid | default() }}/{{ region }}/{{ buildenv }}/"
