---

- name: hostconfig | swap disabling
  block:
    - name: hostconfig | Disable swap for current session
      become: true
      command: swapoff -a

    - name: hostconfig | Remove swapfile from /etc/fstab
      become: true
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items: ["swap", "none"]

    - name: hostconfig | Set kernel swappiness to 0
      become: true
      sysctl:
        name: vm.swappiness
        value: 0
        sysctl_set: true
        state: present
        reload: true

- name: hostconfig | set unlimited memlock ulimit
  become: true
  pam_limits:
    domain: "{{es_user}}"
    limit_type: '-'
    limit_item: memlock
    value: unlimited
    comment: "unlimited memory lock for {{es_user}}"
  when: es_extra_config['bootstrap.memory_lock'] is defined  and  es_extra_config['bootstrap.memory_lock'] | bool

- name: hostconfig | set nofile ulimit
  become: true
  pam_limits:
    domain: "{{es_user}}"
    limit_type: '-'
    limit_item: nofile
    value: "{{es_max_open_files}}"
    comment: "{{es_max_open_files}} for {{es_user}}"
  when: es_max_open_files is defined

- name: hostconfig | Create Elasticsearch unix group
  become: true
  group:
    name: "{{es_group}}"

- name: hostconfig | Add the Elasticsearch user
  become: true
  user:
    name: "{{es_user}}"
    groups: "{{es_group}}"
    system: true

- name: "hostconfig | Change {{es_data_dir}} data directory ownership "
  become: true
  file:
    path: "{{es_data_dir}}"
    name: "{{es_user}}"
    group: "{{es_group}}"
    mode: 0755
    state: directory
