---

- name: elasticsearch/install-config | Create pid, log and conf directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{es_user}}"
    group: "{{es_group}}"
    mode: "2755"
  with_items:
    - "{{es_pid_dir}}"
    - "{{es_log_dir}}"
    - "{{es_conf_dir}}"
    - "{{es_conf_dir}}/templates"

#Create data directory if mountpoint doesn't exist already
- name: elasticsearch/install-config | Create data dir if it doesn't exist
  become: yes
  file:
    path: "{{es_data_dir}}"
    state: directory
    owner: "{{es_user}}"
    group: "{{es_group}}"
    mode: 0755
  notify: restart elasticsearch

- name: elasticsearch/install-config | Create systemd file
  become: yes
  template:
    src: etc/systemd/system/elasticsearch.service.j2
    dest: /etc/systemd/system/elasticsearch.service
    mode: 0644
    force: yes
  notify:
  - reload systemd configuration
  - restart elasticsearch

- name: elasticsearch/install-config | Create jvm.options file
  become: yes
  template:
    src: opt/elasticsearch/config/jvm.options.j2
    dest: "{{es_conf_dir}}/jvm.options"
    owner: "{{es_user}}"
    group: "{{es_group}}"
    mode: 0644
    force: yes
  notify: restart elasticsearch
  vars:
    es_heap_size: "{{ (ansible_memtotal_mb / 2) | round | int | abs }}m"

- name: elasticsearch/install-config | Create main config file
  become: yes
  template:
    src: opt/elasticsearch/config/elasticsearch.yml.j2
    dest: "{{es_conf_dir}}/elasticsearch.yml"
    owner: "{{es_user}}"
    group: "{{es_group}}"
    mode: '0644'
    force: yes
  notify: restart elasticsearch

- name: elasticsearch/install-config | Create tmpfiles.d
  become: yes
  copy:
    content: |
      d    {{ es_pid_dir }}   0755 {{ es_user }} {{ es_group }} - -
    dest: "/usr/lib/tmpfiles.d/elasticsearch.conf"
    owner: "{{es_user}}"
    group: "{{es_group}}"
    mode: 0644
    force: yes
  notify: restart elasticsearch

- name: elasticsearch/install-config | Create unicast_hosts.txt (don't notify restart)
  become: yes
  copy:
    content: |
      {% for node in master_eligible_nodes %}
      {{ node['hostname'] + '.' + cluster_vars.dns_user_domain if (cluster_vars.inventory_ip=='private' and cluster_vars.dns_server is defined and cluster_vars.dns_server != "") else hostvars[node['hostname']]['ansible_default_ipv4']['address'] }}
      {% endfor %}
    dest: "{{es_conf_dir}}/unicast_hosts.txt"
    owner: "{{es_user}}"
    group: "{{es_group}}"
    mode: 0644
    force: yes

- name: elasticsearch/install-config | Create sysctl.d/elasticsearch.conf
  become: yes
  copy:
    content: |
      vm.max_map_count={{ es_max_map_count }}
    dest: "/usr/lib/sysctl.d/elasticsearch.conf"
    owner: "{{es_user}}"
    group: "{{es_group}}"
    mode: 0644
    force: yes
  notify: restart elasticsearch

#This needs to be set programmatically, or elasticsearch will not start.  A reboot will do it, but not ideal.
- name: elasticsearch/install-config | set vm.max_map_count
  become: yes
  sysctl:
    name: vm.max_map_count
    value: "{{es_max_map_count}}"
    sysctl_set: yes
    state: present
    reload: yes
