---

- block:
    - name: kibana/install-binary | Check kibana installed version
      stat:
        path: "{{kibana_unzip_loc}}"
      register: this_kibana_installed

    - name: kibana/install-binary | Check any kibana installed
      stat:
        path: "{{kibana_home}}"
      register: kibana_link_stat

    - debug: msg={{this_kibana_installed.stat}}
    - debug: msg={{kibana_link_stat.stat}}

    # If it's already installed and latest, do nothing
    # If it's not installed, install
    # If a different version is installed, stop the service and remove the soft link.
    - block:
        - block:
            - name: kibana/install-binary | Stop/Disable kibana
              service:
                name: kibana
                state: stopped
                enabled: no

            - name: kibana/install-binary | Remove the kibana link
              file:
                path: "{{kibana_home}}"
                state: absent
          when: kibana_link_stat.stat.exists and kibana_link_stat.stat.lnk_source == '/opt/kibana-{{kibana_version}}'

        - name: kibana/install-binary | Get kibana artifact
          become: yes
          get_url:
            url: "{{kibana_artifact_location}}"
            dest: "/opt/{{ kibana_artifact_location|basename }}"
          when: use_local_artifact is not defined  or  use_local_artifact|bool==false

        - name: kibana/install-binary | Create the artifact dir if it doesn't exist
          become: yes
          file:
            state: directory
            path: "{{kibana_unzip_loc}}"
            owner: "{{kibana_user}}"
            group: "{{kibana_group}}"
            mode: 0755

        - name: kibana/install-binary | Extract the kibana artifact
          become: yes
          unarchive:
            remote_src: "{{ 'yes' if (use_local_artifact is not defined  or  use_local_artifact|bool==false) else 'no' }}"
            src: "{{ '/opt/' if (use_local_artifact is not defined  or  use_local_artifact|bool==false) else '' }}{{kibana_artifact_location | basename}}"
            dest: "{{kibana_unzip_loc}}"
            owner: "{{kibana_user}}"
            group: "{{kibana_group}}"
            extra_opts: [--strip-components=1]
          notify: restart kibana

        - name: kibana/install-binary | Create the kibana link
          become: yes
          file:
            src: "{{kibana_unzip_loc}}"
            dest: "{{kibana_home}}"
            state: link
            mode: 0755
            owner: "{{kibana_user}}"
            group: "{{kibana_group}}"
          notify: restart kibana
      when: (not this_kibana_installed.stat.exists) or (not kibana_link_stat.stat.exists) or (kibana_link_stat.stat.exists and not kibana_link_stat.stat.lnk_source == kibana_unzip_loc)
  vars:
    kibana_unzip_loc: "/opt/{{ kibana_artifact_location | basename | regex_replace('(.*?)\\.tar\\.gz', '\\1') }}"
