---

- name: hostconfig | Create kibana unix group
  become: true
  group:
    name: "{{kibana_group}}"

- name: hostconfig | Add the kibana user
  become: true
  user:
    name: "{{kibana_user}}"
    groups: "{{kibana_group}}"
    system: true


- include_tasks: install-binary.yml

- include_tasks: install-config.yml

- include_tasks: certs.yml
